version: "3.7"

volumes: 
    mongo-data:

networks:
    wevquery:
        name: wevquery_network

services:

    mongo:
        image: wevquery/mongo
        build: 
          context: .
          dockerfile: docker/mongo.dockerfile
          args:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_ROOT_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_ROOT_PASSWORD}'
            MONGO_INITDB_DATABASE: '${MONGO_DATABASE}'
        container_name: wevquery-mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_ROOT_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_ROOT_PASSWORD}'
            MONGO_INITDB_DATABASE: '${MONGO_DATABASE}'
        ports: 
            - "27017:27017"
        volumes:
            - "mongo-data:/data/db"
        networks: 
            - wevquery
        restart: always
        depends_on: 
            - base

    core:
        image: wevquery/core
        build: 
          context: .
          dockerfile: docker/wevquery.dockerfile
          args:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_ROOT_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_ROOT_PASSWORD}'
            MONGO_INITDB_DATABASE: '${MONGO_DATABASE}'
        container_name: wevquery-core
        ports: 
            - "2929:2929"
        networks: 
            - wevquery
        restart: always
        depends_on: 
            - mongo

    base:
        image: wevquery/base
        build: 
            context: .
            dockerfile: docker/base.dockerfile
        container_name: wevquery-base

    # mongo-express:
    #     image: mongo-express:3.6
    #     restart: always
    #     ports:
    #         - 8081:8081
    #     environment:
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: example
            